TODO.md, init/bootstrap.go, init/utils.go, kurma-server.go, stage1/container/container_operations.go, stage1/server/server.go, stage2/clone.c, stage2/mount.c, stage2/spawner.h, stage3/chroot_request.c, stage3/chroot_request_test.go, stage3/cinitd.h, stage3/client/client.go, stage3/client/client_test.go, stage3/client/launcher.go, stage3/helpers.c, stage3/mount_request.c, stage3/mount_request_test.go, stage3/request.c
This changes the way the filesystem is scoped from using pivot_root to instead
bind mount the directory over itself, and then move it to the root. This
approach is simpler and less black magic than pivot_root, and also resolves
the issue we've seen before where multiple contains calling pivot_root at the
same time is racey.
This also changes how host filesystem access is setup in privileged mode.
Previously, it just left the old host filesystem mounted with pivot_root.
Now, have added a new MOUNT command to the stage3 init process. With this, the
stage1 can ask the stage3 to perform the bind mounts before it performs the
chroot.
It will now set up /host/pods going directly to the pods filesystem (read-
only). It will also set up /host/proc to be the proc partition of the host.
Note the …
=> Replace use of pivot_root with mount and move.

init/bootstrap.go, stage1/container/container_operations.go, stage1/container/manager.go
This adds volume support to Kurma, in line with the AppC specification for the
image and pod metadata. This support basic host sourced volumes.
Additionally, privileged contains will now have the volume path read/write
mounted under /host/volumes.
=> Add volume support.

TODO.md, client/api/server.go, client/api/validation.go, client/cli/cli.go, init/bootstrap.go, kurma-cli.go, kurma-server.go, schema/isolator_host_api_access.go, stage1/container/container_isolators.go, stage1/container/container_operations.go, stage1/container/manager.go, stage1/server/server.go
This changes the core Kurma process to use a unix socket for all API access.
This allows the API to be isolated rather than having to rely on notions of
authentication.
Locally, a Kurma process should only be launching very trusted containers and
giving them host API access. Or, the process launching a container for host API
access itself has API access, so Kurma is trusting it.
Generally, if a container process has API access, it should be trusted. This is
one of the base ideas of Kurma as a base building block, and with some initial
trusted containers layering on logic about a broader cluster, and it defining
what the local host should trust or not.
The kurma-api process has been updated to proxy to the local host unix socket
from its TCP socket. It also rejects any container requesting …
=> Change direct API from TCP to unix socket based.

TODO.md, client/api/rpc_enter.go, client/cli/commands/enter/cmd_enter.go, stage1/client/byte_stream.go, stage1/client/init.pb.go, stage1/client/init.proto, stage1/container/container.go, stage1/server/rpc_enter.go
This updates the "enter" API call to allow it to pass in the command that
should be executed.
Previously, the command was hard coded /bin/bash, however this was a bad
assumption as some containers may simply be busybox based and have /bin/sh.
Additionally, there are plenty of cases where the user may with to execute
something specific other than a shell, so the API has been updated to allow
the command to be provided.
If no command is provided, the base assumption has been changed to use /bin/sh.
=> client/stage1: Add support for the "enter" command to be passed in the command

TODO.md, stage1/container/container.go, stage1/container/container_isolators.go, stage1/container/container_operations.go, stage1/container/utils.go, stage2/client/client.go, stage2/clone.c, stage2/doc.go, stage2/spawner.h, stage2/startup.c, stage2/util.c, stage3/cinitd.h, stage3/client/client.go, stage3/client/client_test.go, stage3/doc.go, stage3/helpers.c, stage3/start_request.c, stage3/start_request_test.go, stage3/status_request_test.go, stage3/wait_request_test.go, util/capability/cap.go, util/capability/cap_test.go
This adds support for the CPU and memory resource isolators through
cgroups.
This also adds support for Linux capabilities isolators, to either
specify the retained or the revoked set of capabilities. Capabilities
will be applied within the stage3 process on START requests. It won't
apply it to the stage3 process itself, as the scoped capabilities may
prevent it from the starting the application.
This also adds support for capabilities to the stage2 process. This is
used with the enter command, and ensures entering the container
preserves the intended capabilities.
=> Adds support for resource and capability isolators.

Makefile, build/aci/kurma-stager-container/build.sh, stager/container/common/types.go, stager/container/core/container.go, stager/container/core/core.go, stager/container/core/isolators.go, stager/container/core/util.go, stager/container/main.go, stager/container/run/run.go
Restructured the container stager to focus on each of the call in points
being a package and a single executable main function.
With this, each package will be able to test individually rather than
multiple main() functions everywhere.
Additionally, with a single executable that switches off of os.Args[0],
the size of the stager's ACI image is reduced by about 35%.
FYI PR
=> stager: Restructured the container stager to a single executable

kurmad/kurmad.go, kurmad/runner.go, pkg/backend/interfaces.go, pkg/podmanager/manager.go, testing/integration/lib/kurma/server.rb
This adds signal handling for SIGTERM, SIGINT, and SIGQUIT to perform a
graceful shutdown, including tearing down all of the running pods.
In the future, plan on instrumenting restarting without tearing down
pods (likely with a SIGUSR1) and reloading configuration (likely
SIGHUP).
This adds a Shutdown method to the PodManager interface. The
implementation makes sure to leave the networking pod for last, so that
all other pods will be able to have their networking deprovisioned
properly.
Also changed the integration tests to use SIGTERM rather than
SIGQUIT. It generally is a better fit.
FYI PR
=> kurmad: Add support for signal handling to do clean shutdown

Makefile, README.md, build/aci/kurma-api/manifest.yaml, build/local-kurmad.yml, build/run.sh, kurmad/runner.go, pkg/aciremote/remote.go, stager/container/core/container.go
Added 'make help' which will print out a short help message.
Added 'make run' which will launch kurma-server and allow you to connect
up to it. On Linux, it will run it locally and print the path to the
socket. On other, it'll run Docker and print how to connect to the api
proxy.
Added some updates to the readme with documentation on developer setup.
Update the api-proxy ACI to run within the local dev mode.
Update kurmad setup to handle relative paths in the configuration for
directory entries (pods, volumes, images).
@mbhinder @olegshaldybin @jdreno for review
=> Updates for developer documentation.

init/bootstrap.go, init/config.go, init/constants.go, init/utils.go, kurmad/kurmad.go, kurmad/runner.go, pkg/backend/interfaces.go, pkg/capabilities/capabilities.go, pkg/networkmanager/driver.go, pkg/networkmanager/util.go, pkg/podmanager/manager.go, schema/isolator_linux_namespaces.go, stager/container/core/core.go
This includes the code level changes to update kurmaOS to be compatible
with the pods functionality and to update its configuration handling for
parity with kurmad. The build scripts will be added separately.
The changes include:
* Ensure the container stager flushes logs before exiting on error.
* Ensure the set of available capabilities is refreshed in
`pkg/capabilities` after `/proc` has been mounted in kurmaOS. The
underlying library has a package `init()` function which was reading
`/proc` to determine the last capability supported. However with kurmaOS,
`/proc` is not yet mounted when that will run. This changes the init
handling to have it refresh after the system mounts are set up.
* Dynamically read the available cgroup mount types from `/proc/cgroups`
instead of using a hard …
=> Updates for kurmaOS with the pod model

testing/integration/lib/kurma/api_client.rb, testing/integration/lib/kurma/cli_client.rb, testing/integration/lib/kurma/server.rb, testing/integration/spec/create_spec.rb
This addresses a few improvements with the integration tests.
* Redirect the HTTP request logging to the test log. Reduces noise in
the testing output and puts it in line with the other calls in the
log.
* Use the CLI/kurmad binaries from the repositories bin directory rather
than finding them on the path. This makes running the tests simpler.
* Update the create_spec.rb tests to get the created pod's UUID from the
create calls output, rather than assuming its the first pod returned
from the API. It could be easily stopping a pod that wasn't the one it
started.
FYI PR
=> testing: A couple integration test hardness improvements

pkg/cli/commands/create.go, pkg/podmanager/dnsconfig_unix.go, pkg/podmanager/operations_test.go, pkg/podmanager/pod.go, pkg/podmanager/pod_operations.go, stager/container/core/util.go, testing/integration/spec/networking_spec.rb
This adds support for populating the resolv.conf in the podmanager
when it is setting up the stager. It will look for a returned DNS
configuration from the networkmanager and use that. If none is found,
then it will parse the host's resolv.conf and use that to write a
resolv.conf for the stager. It does this rather than mount in the
resolv.conf to ensure it is scoped to the necessary settings.
The stager has also been updated to simply bind mount its resolv.conf
into the individual applications. It is mounted as read only so apps
cannot alter it.
Unit tests added around the podmanager's setup for the
stager. Integration test added to ensure it works all the way down
through to the app containers.
A small change was included to allow `kurma-cli create` to take
additional arguments which …
=> Add support for populating the resolv.conf in pods

stager/container/run/run.go, testing/integration/spec/create_spec.rb
This fixes an issue where the 'run' callin to the container stager could
exit when the child process is done, but not before the goroutines to
copy data over the tty are finished writing.
This adds a waitgroup around copying from the tty to stdout and ensures
it has finished before the process exits.
Additionally, added a simple integration test that will enter a
container and simply run `whoami`. This is just a simpler test to
validate the 'enter' command than testing the resolv.conf writing.
Fixes #56
=> stager/container: Ensure output is written before exiting

pkg/cli/commands/enter.go
@krobertson I was not able to do a cli enter. This fix works but only for the "bridge" network plugin pod. It does not work for any other pods I create. This is the error I get, looks like it's looking for bin/sh. 
ERR: exec: "/bin/sh": stat /bin/sh: no such file or directory
=> kurma-cli enter would panic if user did not specify all three: UUID,

Documentation/network_specification.md, build/aci/console/manifest.yaml, build/aci/kurma-api/manifest.yaml, build/aci/kurma-stager-container/manifest.yaml, build/aci/kurma-upgrader/manifest.yaml, build/kurma-init/kurma.yml, build/local-kurmad.yml
This moves the image name references from apcera.com/kurma/* to using
kurma.io.
=> build: Change all references to ACI names to use kurma.io

build/docker/kurma-stage4/build.sh
Updates the stage4 Docker image to pull in Go 1.6.1.
This release of Go primarily addressed an issue with Go's crypto
libraries not validating some inputs before using them, which could be
used as a remote DoS. Filed as CVE-2016-3959.
FYI PR
=> stage4: Updated to Go 1.6.1

pkg/apiclient/types.go, pkg/backend/interfaces.go, pkg/daemon/pod_service.go, pkg/podmanager/pod.go
This adds the network results object to the Pod object returned by the
daemon's API. This allows visibility into the network information
configured for a pod.
Note: when sharing the host's network namespace, the network info will
be empty, as nothing was configured for that pod.
FYI PR
=> Add network information to Pod object returned over the API.

README.md
Adds a brief section to the readme to cover how to run both the unit
tests and the integration tests.
FYI PR
=> readme: Add section on running the unit and integration tests

pkg/podmanager/utils.go
On some platforms, such as Ubuntu Xenial, the cgroups location defaults
to being shared. The mapping in of cgroups can then cause an exponential
growth of the mountinfo file which causes large CPU spikes parsing it on
container spin up.
This ensures the cgroups mounts that are mapped in are private and do
not propagate. This is controlled just at the launching of the stager by
the podmanager.
FIY @schancel @mbhinder
=> podmanager: Ensure cgroups mounts are private

testing/integration/spec/create_spec.rb, testing/integration/spec/networking_spec.rb
Change container teardown in the integration tests to be a part of the
cleanup operations. This ensures that the containers are stopped even in
the case of a test failure, since otherwise if there is a failure, the
remaining steps won't run.
@zquestz @mbhinder
=> spec: Fix container shutdown to be a cleanup operation

build/docker/kurma-kernel/build.sh, build/docker/kurma-kernel/patches/0002-security-provide-copy-up-security-hooks.patch, build/docker/kurma-kernel/patches/0003-overlayfs-use-copy-up-security-hooks.patch, build/docker/kurma-stage4/build.sh
Updates the base build image to use Go 1.6.2.
Updates the kernel image to use the 4.6.2 kernel.
FYI PR
=> build: Updates to build images for kernel and Go

build/packer/ubuntu/scripts/01_packages.sh, pkg/daemon/general_service.go, pkg/graphstorage/aufs/aufs.go, pkg/graphstorage/overlay/overlay.go, pkg/misc/kernelversion.go, stager/container/core/container.go
This adds support for aufs as a graphstorage implementation. This
enables Kurma to work on Ubuntu 14.04 and 12.04.
The container stager has also been updated to default to automatically
detecting which driver to use, if one isn't explicitly defined.
A few updates have been made to the Ubuntu packer definitions for Ubuntu
14.04 and 12.04. On both, the cgroup-lite package was installed to
ensure all cgroups mounts are available on boot. Additionally, the 12.04
defintion will install the 3.13 kernel from Ubuntu trusty. By default,
12.04 used the 3.2 kernel, which is older than kernels typically
recommended for container workloads for full and stable functionality.
Fixes #33.
@alextoombs @mbhinder
=> Add support for aufs to graphstorage.

build/packer/README.md, build/packer/debian/scripts/01_packages.sh, build/packer/debian/scripts/02_install_ruby.sh, build/packer/debian/scripts/03_s3cmd.sh, build/packer/debian/scripts/99_cleanup.sh, build/packer/debian/template.json
This adds packer build scripts for Debian. These should work against
Debian 8.0/jessie as well as the upcoming 9.0/stretch.
FYI PR, merging after the test posts to the build. Only adds packer definitions, current master is green on Debian.
=> packer: Add build scripts for Debian.

build/packer/centos/scripts/04_ssh.sh, build/packer/centos/template.json
Updates the CentOS build scripts to not require a tty for sudo
access. This causes issues with vagrant-aws and rsyncing, even with the
Vagrantfile specified to use a tty.
FYI PR
=> packer: Update CentOS to not require tty for sudo

pkg/aciremote/remote.go
@krobertson @alextoombs 
The transport defined in that package has a timeout of 5 seconds, which was causing
package discovery to time out on my VM which has a slow network.
=> discovery: override the http.Client transport in the discovery package.

stager/container/core/util.go
This adds support for the readOnlyRootFS flag on a pod to configure the
application's root to be read-only. This parameter was added in the
0.8.1 spec.
FYI PR
=> stager: Add support for readOnlyRootFS on Pod Manifest

Makefile, build/release/README.md, build/release/example-kurmad.yml, cmd/kurmad.go
This updates the release make tasks to generate releasable
tarballs. These include the license file as well as all the necessary
dependencies and example configuration, such as for the main kurmad
release.
Previously, the release just generated the set of binaries just loosely
in a directory, but not a single file that could be downloaded,
extracted, and utilized.
FYI PR
=> makefile: Updated release handling to build tarballs

pkg/cli/commands/list.go
Updates the list command to show any IP addresses that were provisioned
from network plugins for the pod.
@alextoombs @wallyqs
=> cli: Add listing the pod's IPs in the list command

build/docker/kurma-kernel/build.sh, build/kurma-init/kurma.yml
This updates the kurma-kernel docker image to use the 4.6.3 kernel.
This also updates some default configuration in kurmaOS to match latest
CNI, as well as ensuring the comments module for iptables is loaded in
at boot.
FYI PR
=> kurmaos updates for kernel 4.6.3 and configuration tweaks.

build/aci/cni-netplugin/build.sh, build/aci/cni-netplugin/manifest.yaml
It may be necessary for iptables to attempt to load some kernel modules
if they aren't already present. To help this function, adding the host
privilege isolator to the CNI image's manifest and the necessary
symlinks.
FYI PR, needed for #92
=> cni: Ensure modules are available for iptables

pkg/networkmanager/driver.go, pkg/podmanager/pod_operations.go, pkg/podmanager/utils.go, testing/integration/lib/kurma/api_client.rb, testing/integration/spec/networking_spec.rb
The CNI modules will default to returning a result including `"dns:"{}`,
which will cause the DNS property on the result ot be populated with an
empty object rather than nil.
This adds a work around which iterates over all of the DNS object's
fields and if all of them are blank/empty, it will use the host's
resolv.conf settings.
This changes some of the system tests so that the resolv.conf check is
done with both host networking and isolated networking, currently using
the default included bridge network. In time, will likely have multiple
networks defined in the testing config for testing more networking
modes/settings.
@wallyqs @jpoler
=> podmanager: Fix an issue with resolv.conf when using an isolated network

pkg/apiclient/types.go, pkg/apiproxy/container_enter.go, pkg/cli/commands/enter.go, pkg/daemon/container_enter.go, stager/container/main.go, stager/container/run/run.go, testing/integration/spec/create_spec.rb
This updates the container stager to properly return the exit code from
the process it was executing. Previously, the caller was always getting
a zero exit code rather than the actual one.
This also adds support for returning the exit code on container enter
requests over the API/CLI. This way, the CLI will exit with the same
code as the process it was running in the container.
An integration test has been added to test the exit code handling
propagating.
@alextoombs @wallyqs @jpoler
=> stager/api: Add support for returning the exit code on run calls

cmd/kurmad.go, kurmad/runner.go, pkg/networkmanager/manager.go, pkg/podmanager/manager.go
Changes format of logging string for kurmad, sets the pod field among other minor logging related changes.
@krobertson
=> Tweaks to logging around Kurma managers

build/docker/kurma-stage4/build.sh
This will allow us to run docker containers from within the kurma-stage4 image (which is used for running build steps in CI).
The binding mounting of the docker socket will occur on container creation and had already been added in the CI config.
=> Add docker client to kurma-stage4 image.

build/packer/centos/template.json, build/packer/debian/template.json, build/packer/fedora/template.json, build/packer/ubuntu/template.json
This adds explicitly setting delete_on_termination to all the packer
templates. Without this specified, it was copying the setting from the
source image. On all of the source images except for CentOS, this was
enabled by default.
However, without it enabled on CentOS, CI integration test runs were
leaving behind volumes on AWS for each run.
Explicitly setting this will ensure it is always enabled.
FYI PR
=> packer: Specify delete_on_termination in packer templates

kurmad/runner.go, pkg/podmanager/manager.go, pkg/podmanager/pod_operations.go
Idea on using `debug` toggle to follow the stager debug logs in the kurmad log output /cc @krobertson @jpoler
=> Add stager debug logs into kurmad output with debug flag

testing/integration/spec/networking_spec.rb
Had left in a line of code that was printing the API response. Not
necessary anymore and didn't remove it before merging. Oops!
FYI PR, will merge on green.
=> testing: Remove puts from networking test

testing/integration/lib/kurma/server.rb
This enables the debug flag in integration tests to have the stager
output written to kurmad's log. This will hope expose messages from the
stagers inline with the kurmad process.
FYI PR, will merge on green... cc @wallyqs
=> testing: Enable the debug flag in integration tests

build/docker/deb/make-deb-package.sh, build/docker/rpm/make-rpm-package.sh
This removes adding the kurma-upgrader ACI image in the deb/rpm package
builds. This image is used to upgrade a kurmaOS host, so it is not
relevant to the kurmad packages. It also greatly bloated the size of the
packages.
Fixes #110 
FYI PR @jpoler
=> build: Don't include the kurma-upgrader ACI in deb/rpm packages

build/local-kurmad.yml, stager/container/init/init.c
This fixes an issue where the init process wasn't properly handling the
return from a signal handler. The pause(2) documentation clearly states
the pause call only returns when the process was interrupted by a signal
and the signal handler has finished running.
In this case, pause will verify it returned due to a signal handler and
re-run pause.
This also adds a loop to waitpid in the sigchld signal handler to
properly reap the pid.
Also updated the local configuration file used with `make run` to enable
debugging.
A follow up PR will be posted to fix the "run" call returning
immediately with a forked process, and at that time I'll add an
integration test around the behavior.
@wallyqs @mbhinder
=> stager: Fix issue with init handling returns from signal handlers

pkg/cli/cli.go, pkg/cli/commands/image_list.go, pkg/cli/commands/list.go, pkg/cli/commands/status.go
This updates kurma-cli to search multiple locations for the default
socket location. Previously, it always searched for
/var/lib/kurma/kurma.sock.
However with the prebuilt deb and rpm packages, they may often be at
/var/run/kurma.sock, more in line with that distro's recommendations or
what not.
It will now search /var/lib/kurma.sock and /var/run/kurma.sock, and go
with whichever one exists.
This also fixes a few locations that were missing newlines around error
messages in the cli.
@wallyqs @mbhinder
=> cli: Update kurma-cli to search multiple locations for the kurmad socket

build/aci/kurma-api/build.sh, build/aci/kurma-stager-container/build.sh, build/aci/kurma-upgrader/build.sh
The kurma-api, kurma-upgrader, and stager-container ACI images were
missing version labels being set at build time.
This ensures the value gets set at build time if there is a VERSION
environment variable.
@wallyqs @alextoombs @mbhinder 
Last thing I noticed when testing the release. This matches what was being done for the console ACI at build time.
=> build: Ensure last ACIs get version labels at release build time

README.md
Just noticed it while installing Kurma onto my new Vagrant VM.
FYI PR
/cc @wallyqs @krobertson
=> readme: fix typo pointing to website

pkg/cli/commands/create.go, pkg/image/fetch.go, pkg/image/fetch_test.go, pkg/remote/aci/pull.go, pkg/remote/aci/pull_test.go, pkg/remote/docker/pull.go, pkg/remote/docker/pull_test.go, pkg/remote/http/pull.go, pkg/remote/puller.go
Previously, every time we pulled a Docker image, we would squash the layers into a single ACI. We want to be able to eventually re-use common layers across different docker images.
This PR doesn't expose the option to users; it just adds some plumbing.
@krobertson @wallyqs @mbhinder
=> Update `Pull` to handle multi-layer images
